### ISSUE TITLE
Package Request: cavezofphear

### ISSUE THREAD

**Issue by T4P4N** [termux/game-packages#15]
**Package description**
ASCII Boulder Dash clone

**Link to home page and sources**
1. Home page: https://packages.debian.org/source/jessie/cavezofphear
2. Source code: http://deb.debian.org/debian/pool/main/c/cavezofphear/cavezofphear_0.5.1.orig.tar.gz

**Additional information**
Have you compiled or tried to compile the package on device?
Yes. And It worked.

**Comment by T4P4N** [comment]
![Screenshot_Termux_20190329-114036](https://user-images.githubusercontent.com/32695903/55336689-00c46800-54bb-11e9-9c36-7c43851dbd5f.png)

**Comment by Grimler91** [comment]
Thanks for the tip!

I've pushed the package to the repo so it should be available on both branches as soon as the builds finish!
