### ISSUE TITLE
Nethack: Not working

### ISSUE THREAD

**Issue by kenneth-Q** [termux/game-packages#20]
I found a bug.
I run nethack and create a role. Then I cannot continue and output these information:

> Program initialization has failed.
To report this error, contact root or games.
Dungeon description not valid.

Here, I provide a log file from strace command: [here](https://github.com/termux/unstable-packages/files/2940913/nethack.log)

 **Another information:** 
Updatable packages:
All packages up date
System information:
Linux localhost 3.4.0-7532458 #1 SMP PREEMPT Wed Mar 16 12:53:31 KST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.0
Device manufacturer:
samsung
Device model:
SM-N9007

I have no idea to fix it. Thank you.

**Comment by xeffyr** [comment]
Found another error:
```
$ nethack
WARNING: linker: /data/data/com.termux/files/usr/games/lib/nethackdir/nethack: unused DT entry: type 0x1d arg 0x74d5
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "/data/data/com.termux/files/usr/games/lib/nethackdir/nethack"...
page record for 0xb6d2902c was not found (block_size=16)
```

termux-info:
```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.4.113-g955ea3f #1 SMP PREEMPT Sat Jun 30 09:25:00 UTC 2018 armv7l Android
Termux-packages arch:
arm
Android version:
6.0.1
Device manufacturer:
Asus
Device model:
Nexus 7
```

@Grimler91

**Comment by Grimler91** [comment]
I can reproduce the "Program initialization has failed" error but not the memcpy error (tried on arm android 7) @xeffyr does that happen right after you run nethack?

**Comment by bhagwandassony1** [comment]
![Screenshot_20200804-215851](https://user-images.githubusercontent.com/69147279/89324057-2bf23500-d676-11ea-80dd-d867d7cd88aa.png)

**Comment by bhagwandassony1** [comment]
🐃(RKB)(^).
