### ISSUE TITLE
Frotz is no longer working

### ISSUE THREAD

**Issue by IntyLab** [termux/game-packages#21]
I had last used it a couple weeks ago.  Now, when I try to launch it, I get the error message:

CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by "frotz"...

I tried uninstalling and reinstalling the package, but that didn't change anything.

**Comment by xeffyr** [comment]
@Grimler91 Frotz doesn't work on ARM Android 6.

**Comment by IntyLab** [comment]
Okay.  I still consider myself a noob after all these years.

Frotz was running on my old tablet before.  I installed it on my phone and it seems to be working fine.  Thanks for your help.

**Comment by Grimler91** [comment]
Hm, weird

**Comment by xeffyr** [comment]
@IntyLab @Grimler91 I have fixed it on android-5 branch, now seems working.

**Comment by IntyLab** [comment]
I tried it on my tablet and it is working now.  Meanwhile, I found glulxe and installed it, and the same thing is happening there.  It works on my phone, so now I can play the Andromeda games!  Too bad it doesn't use SDL.
