### ISSUE TITLE
Greed and Moon-buggy issue.

### ISSUE THREAD

**Issue by HoangPhantom** [termux/game-packages#22]
Hello, I'm trying to use greed and/or moon-buggy to play but when I enter them in the terminal, neither of them works. It always say:
CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by "greed"...
CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by "moon-buggy"...

**Comment by Grimler91** [comment]
Thanks for reporting! Updated packages should be available in a few minutes, when [the build](https://gitlab.com/Grimler/game-packages/pipelines) finishes, please try them

**Comment by HoangPhantom** [comment]
Thank you very much
