### ISSUE TITLE
Bastet is linked to an outdated version of Boost

### ISSUE THREAD

**Issue by JacobTDC** [termux/game-packages#23]
It's as simple as the title. Bastet is linked to `libboost_program_options.so.1.69.0`, but the current version of Boost is `1.70.0`.

**Comment by Grimler91** [comment]
Thanks for reporting! I've bumped the package, it should be available in 15 min or so (as long as [the builds](https://gitlab.com/Grimler/game-packages/pipelines) succeed)

**Comment by JacobTDC** [comment]
All works as it should, now. Thanks! You wouldn't believe how many times I've tried to play it since it broke.
