### ISSUE TITLE
Package Request: dopewars

### ISSUE THREAD

**Issue by T4P4N** [termux/game-packages#26]
**Package description**
drug-dealing game set in streets of New York City

**Link to home page and sources**
1. Home page: https://dopewars.sourceforge.io
2. Source code: http://packages.debian.org/unstable/games/dopewars.html
3. Its-pointless repo: https://github.com/its-pointless/its-pointless.github.io/tree/master/files/dists/termux/extras/binary-aarch64

**Additional information**
Have you compiled or tried to compile the package on device?
Actually i've tried it using its-pointless repo, and its working fine, But I think it should be also available in official game-repo. :)

**Comment by RossComputerGuy** [comment]
Oh I remember Druaga1 mentioning this game, I think Open GL is needed which I don't think works.

**Comment by T4P4N** [comment]
As per its-pointless's repo here is the package details:
```
Package: dopewars
Architecture: aarch64
Installed-Size: 476
Maintainer: Fredrik Fornwall @fornwall
Version: 1.5.12-1
Homepage: https://dopewars.sourceforge.io
Depends: libandroid-support, ncurses, glib, pcre
Description: drug-dealing game set in streets of New York City
Filename: dists/termux/extras/binary-aarch64/dopewars_1.5.12-1_aarch64.deb
Size: 199738
MD5Sum: afc4aedee53920b4fff6c51380dd06c2
SHA1: decff78cdf55b55c39cf32ec7fdb993850cd438f
SHA256: 555f9f2f69c53d5c29f9c44013d3fff0aef6d04577a643abf73cb107439fc8ce
SHA512: e5e6959747881ca5765addbeb6365e1da41bd0c775d728ed1ea259dc9e89bb0cad3ac09bd33b7c4d9a7ea773d2eac66143a40e8f7ba27b184035e09ac4f92d06
```

**Comment by Grimler91** [comment]
Dopewars has been added to the master branch (android-7 and newer repo), and will probably be added to the android-5 branch within a few days (I just need to backport the updates I pushed in https://github.com/termux/game-packages/pull/38). Thanks for requesting and providing the package details!

**Comment by T4P4N** [comment]
Thank you very much !! :+1:
