### ISSUE TITLE
nethack fails on initialisation

### ISSUE THREAD

**Issue by jean** [termux/game-packages#27]
After character generation:

```
Configuration incompatibility for file "dungeon".
Oops...

Hit space to continue:
```

Terminal output:

Program initialization has failed.
To report this error, contact root or games.
Dungeon description not valid.

**Problem description**

`nethack` fails to start game.

**Steps to reproduce**

`nethack`,  `y`, `y`

**Expected behavior**

Game starts.

**Additional information**
Post output of command `termux-info`.

All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
System information:
Linux localhost 3.18.14-14598364 termux/termux-packages#1 SMP PREEMPT Mon Nov 19 18:25:18 KST 2018 armv8l Android
Termux-packages arch: arm
Android version: 8.1.0
Device manufacturer: samsung

**Comment by Grimler91** [comment]
Thanks for reporting! This has been fixed in https://github.com/termux/game-packages/commit/0e3a45608baabe51c26429e3b8de7d3b812f3324.
