### ISSUE TITLE
package request: vitetris

### ISSUE THREAD

**Issue by soredake** [termux/game-packages#28]
**Package description**
vitetris is a terminal-based Tetris clone by Victor Geraldsson. Gameplay is much like the early Tetris games by Nintendo.

**Link to home page and sources**
1. Home page: http://victornils.net/tetris/
2. Source code: https://github.com/vicgeralds/vitetris

**Additional information**
Have you compiled or tried to compile the package on device? Yes, configure and make enough to build it.

**Comment by Grimler91** [comment]
Has now been added to both repo branches. Thanks for requesting!
