### ISSUE TITLE
Dopewars "invalid system call"

### ISSUE THREAD

**Issue by uxcn** [termux/game-packages#41]
Dopewars is trying to execute an invalid system call (killed with `SIGSYS`) on Android Q.

**Comment by Grimler91** [comment]
Thanks for reporting! Could you install `strace`, run `strace -o dopewars.log dopewars` and share the log there?

**Comment by uxcn** [comment]
Here's the [strace](https://github.com/termux/game-packages/files/3890356/dopewars.log).

**Comment by Grimler91** [comment]
Should be fixed in 1.5.12-1 which will be available shortly! Thanks again
