### ISSUE TITLE
Can not subscribe

### ISSUE THREAD

**Issue by draxaris1010** [termux/game-packages#5]
I can not subscribe to the repo.
This is what I got:

```
$ pkg install game-repo
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/xeffyr/x11-packages-21 x11 InRelease
Get:3 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release [6055 B]
Hit:3 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
142 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package game-repo
```

**Comment by Grimler91** [comment]
Hi, yes, the game-package isn't added to termux-packages yet, here is the PR: https://github.com/termux/termux-packages/pull/3313

I'm also currently looking at moving the repo to [bintray](https://bintray.com/beta/#/grimler/game-packages-21?tab=packages). 
The plan is to have the repo up and running during the weekend. 

If you want to test it out before that then you can always do 
```
echo "deb https://grimler.se root stable" > $TERMUX_PREFIX/etc/apt/sources.list.d/games.list
```
and then `apt update`. I will probably stop updating the repo once the bintray repos are functional though (but at that point you can just do `pkg in game-repo` to get updates)

**Comment by draxaris1010** [comment]
I tried your commands but they don't work, this is what I got:

```
$ echo "deb https://grimler.se games stable" > $TERMUX_PREFIX/etc/apt/sources.list.d/games.list
bash:  /etc/apt/sources.list.d/games.list: No such file or directory
```

**Comment by Grimler91** [comment]
Ah, sorry again, It's suppose to be $PREFIX, not $TERMUX_PREFIX

**Comment by draxaris1010** [comment]
I tried that as well but it doesn't seems to work,
```
echo "deb https://grimler.se games stable" > $PREFIX/etc/apt/sources.list.d/games.list
bash:  /data/data/com.termux/files/usr/etc/apt/sources.list.d/games.list: No such file or directory
```

**Comment by Grimler91** [comment]
Ah, I guess `/data/data/com.termux/files/usr/etc/apt/sources.list.d` didn't exist before. What's the output of `head /data/data/com.termux/files/usr/etc/apt/sources.list.d/games.list` now?

**Comment by draxaris1010** [comment]
The output is:
```
$ head /data/data/com.termux/files/usr/etc/apt/sources.list.d/games.list
deb https://grimler.se games stable
```

**Comment by Grimler91** [comment]
Hm, weird, it looks alright to me. 

Anyways, the package `game-repo` has now been added to the main repo, so you can install it with `pkg in game-repo` :+1:
