### ISSUE TITLE
nethack save folder present but Shift-S still failing

### ISSUE THREAD

**Issue by David-Duffy** [termux/game-packages#63]
**Problem description**
I am still encountering "Saving... Cannot open save file" despite the fact that 
/data/data/com.termux/files/usr/games/nethackdir/save 
was automatically created, and I subsequently made it world writable after first encountering the problem. 
I just reinstalled without improvement.

**Additional information**

Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
busybox/stable 1.32.0-3 aarch64 [upgradable from: 1.32.0-2]
debianutils/stable 4.11.2 aarch64 [upgradable from: 4.11.1]
grep/stable 3.5 aarch64 [upgradable from: 3.4-1]
openssh/stable 8.3p1-2 aarch64 [upgradable from: 8.3p1-1]
resolv-conf/stable 1.3 aarch64 [upgradable from: 1.2-1]
termux-api/stable 0.52 aarch64 [upgradable from: 0.50-2]
termux-tools/stable 0.95 all [upgradable from: 0.94]
Android version:
10
Kernel build information:
Linux localhost 4.9.190+ #1 SMP PREEMPT Fri Aug 14 18:18:50 CST 2020 aarch64 Android
Device manufacturer:
HMD Global
Device model:
Nokia 2.2

**Comment by Grimler91** [comment]
Thanks for reporting!

Not sure why it fails yet, code looks alright to me. Might work if I hardcode the save path, it is currently using a relative path vs the nethack binary, will investigate more

**Comment by Grimler91** [comment]
Should work now in 3.6.6-3, thanks for reporting!
