### ISSUE TITLE
games/dMagnetic

### ISSUE THREAD

**Issue by dettus** [termux/game-packages#66]
Hello. I have this small project dMagnetic. It allows users to play classic Text Adventures like "The Pawn", "The Guild of Thieves", "Jinxter", "Myth", "Fish!", "Corruption" and "Wonderland" on modern devices. I loved those games when I was a child.
Since it is a Terminal application, it would fit perfectly into your repository.

I would be honoured if you could drop me a line and tell me what your thoughts are.

**Package description**
Describe what this package do and why it should be available.
It is an interpreter, the re implementation of the original virtual machine. It is not a game in itself. People would still need the original binaries.

**Link to home page and sources**
1. Home page: https://www.dettus.net/dMagnetic
2. Source code: https://www.dettus.net/dMagnetic/dMagnetic_0.29.tar.bz2

**Additional information**
Have you compiled or tried to compile the package on device?
No. I am sorry. But it should not be a problem.

* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by Grimler91** [comment]
Hey, cool, thanks for the tip. I'll have a look at packaging it!

**Comment by dettus** [comment]
Wonderful!
There is a "make check" target which tells you if it would be possible. (You would probably haven to run 'make SHA256_CMD=sha256sum check' though...)

**Comment by Grimler91** [comment]
Added in https://github.com/termux/game-packages/commit/04d5ae3486349b52372624bebd169cdff241b888!

Apart from the standard PREFIX patches I also [modified Makefile to respect the DESTDIR variable](https://github.com/termux/game-packages/blob/master/packages/dmagnetic/Makefile.patch). DESTDIR allows distro maintainers to `configure` and `make` projects for some prefix (`/usr/`) and then install to another prefix (something like `/path/to/build/dir/usr/`) for easy packaging into a deb/tar/rpm/similar. You might want to consider adding that patch or something similar to your code.

Do you have a git (or other vcs) publicly available somewhere?

**Comment by dettus** [comment]
Hello.

WONDERFUL! THANK YOU SO SO VERY VERY MUCH!!!  :D
Yes, I am hosting my project on Github, albeit not as a public repository. My apologies. I like it that way, since it gives me the freedom to do some experiments without having to worry about my appearance. :)

As for the INSTALLDIR patch: DESTDIR is actually the BSD-style! My main development environment is OpenBSD, so I am following their rules. (I am applying the same patch to the Debian package as well. )

Hopefully it still meets your standards?

One more question: What is your procedure regarding updates?

**Comment by Grimler91** [comment]
> Yes, I am hosting my project on Github, albeit not as a public repository. My apologies. I like it that way, since it gives me the freedom to do some experiments without having to worry about my appearance. :)

Alright, I understand.

> Hopefully it still meets your standards?

Yeah, it is fine :+1: 

> What is your procedure regarding updates?

Normally I have a look on https://repology.org/projects/?inrepo=termux&outdated=1 every now and then to see which packages are outdated. Not all packages are listed there though, but [dmagnetic is](https://repology.org/project/dmagnetic/versions) so it would show up in that check. 
If you want you can open PRs yourself for updating the package, which just means changing TERMUX_PKG_VERSION and TERMUX_PKG_SHA256 (and in that case you can also set TERMUX_PKG_MAINTAINER to yourself)

**Comment by dettus** [comment]
> If you want you can open PRs yourself for updating the package, which just means changing TERMUX_PKG_VERSION and TERMUX_PKG_SHA256 (and in that case you can also set TERMUX_PKG_MAINTAINER to yourself)

Okay, I'll try it out next time (Already working on release 0.30 ;) ) Regardless if it works or not, I will drop you a line. Once again: Thank you very much for this opportunity!

**Comment by dettus** [comment]
![Screenshot_20201231-083734](https://user-images.githubusercontent.com/369464/103399985-c2eaec80-4b43-11eb-99ba-9709e94a48eb.png)


IT WORKS! <3
