### ISSUE TITLE
games/dMagnetic Thank you! (Not a bug...)

### ISSUE THREAD

**Issue by dettus** [termux/game-packages#68]
![Screenshot_20201231-083734](https://user-images.githubusercontent.com/369464/103400306-ea8e8480-4b44-11eb-873c-b8be70534536.png)

Hello. This is not really a bug. I just wanted to say thank you for porting my project to termux. 

As you can see: It works! :) 

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by kcubeterm** [comment]
Hey man, can you share .GFX and .mag file. 

```sh 
dMagnetic wonderland
*** dMagnetic 0.29
*** Use at your own risk
*** (C)opyright 2020 by dettus@dettus.net
*****************************************

Using .ini file: /data/data/com.termux/files/usr/share/games/dMagnetic/dMagnetic.ini
ERROR: unable to open [/data/data/com.termux/files/usr/share/games/magneticscrolls/wonder.mag]
This interpreter needs a the game's binaries in the .mag and .gfx
format from the Magnetic Scrolls Memorial website. For details,
see https://msmemorial.if-legends.org/memorial.php
Please run with dMagnetic [-ini dMagnetic.ini] GAME
 where GAME is one of
.......

```

**Comment by kcubeterm** [comment]
Ah, found the sources. https://msmemorial.if-legends.org/

**Comment by dettus** [comment]
Hahaha. The link to those is right there in the post. But you can also use .dsk, .atr and d64 files as input!

**Comment by kcubeterm** [comment]
Yea, thanks for info

**Comment by Grimler91** [comment]
> I just wanted to say thank you for porting my project to termux.

Thanks for creating the project and thereby making it easier for people to play classic games :)

> Ah, found the sources. https://msmemorial.if-legends.org/

I have been thinking of writing a small menu script for downloading the different games, [similar to what we have for frotz](https://github.com/termux/game-packages/blob/master/packages/frotz/zgames), would be pretty neat!

**Comment by kcubeterm** [comment]
Yes, menu script will be quite convenient way for users
