### ISSUE TITLE
can't install curse of war from repo.

### ISSUE THREAD

**Issue by sudipta-nandan** [termux/game-packages#71]
**Problem description**
Curse Of War cannot be installed from repo.
On installing it gives an error
"Unable to locate package curseofwar"
I have game-repo installed.

**Steps to reproduce**
`pkg update && pkg upgrade -y`
`pkg install curseofwar`

**Expected behavior**
Install Curse Of War

**Additional information**
Post output of command `termux-info`.

Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# x11-repo (sources.list.d/x11.list)
deb https://ipfs.io/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Tue Sep 22 15:38:19 CST 2020 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
JSN-L42

**Comment by Grimler91** [comment]
The package should be available now. Please let me know if you still have problems

**Comment by sudipta-nandan** [comment]
Yup! Working Fine As intended. Thanks a lot for this!
