### ISSUE TITLE
moria: missing folder

### ISSUE THREAD

**Issue by Ivegottheblues** [termux/game-packages#75]
Hallo everyone,

I would like to play Moria game on my Android device, and a user on reddit suggested me to download Termux, so I discovered this beautiful world. I'm really not into programming or whatever, I would like just to use the game and maybe understand better how Termux work.

Now I downloaded Termux from F-droid, update, downloaded moria running the command pkg install moria. Done.
When I type moria to let the game starts it will give me this error:

Can't open score file '/data/data/com.termux/files/usr/lib/games/moria/scores.dat'

I checked and I give permission to the app. What I have to do? Thank you

**Comment by suhan-paradkar** [comment]
Well.. thats an issue...

**Comment by Grimler91** [comment]
Moria 5.7.14 is now available from at least the grimler.se mirror, and the path to the help files and score files has been fixed
