### ISSUE TITLE
games/dMagnetic -> Update to release 0.31

### ISSUE THREAD

**Issue by dettus** [termux/game-packages#77]
**Package description**
Hey guys! 
So, my little project has seen release 0.31. 
I could update build.sh, replacing the version number and the sha256 sum.
Unfortunately, I noticed that you guys had some patches applied to the source
code, which I cannot guarantee would work.
So I would like to ask you if you could do the honors. ;)

**Link to home page and sources**
1. https://www.dettus.net/dMagnetic/dMagnetic_0.31.tar.bz2 (sha256sum: 1a0356f04d3a5e252225b0fd38b9047957f292f67338ba83579958b46f184139)
2. Source code: https://github.com/termux/game-packages/tree/master/packages/dmagnetic

**Additional information**
Have you compiled or tried to compile the package on device?
* No

**Comment by Grimler91** [comment]
Should be available now!

Sidenote: do you know anything about the legal/license status of the game files? 
I am guessing they are in some sort of limbo, and that I probably should not package them (could have them in a subpackage dmagnetic-games so that users do not have to download them manually)

**Comment by dettus** [comment]
Thank you. 
I must admit, I am already busy working on 0.32 ;)

Regarding the .mag/.gfx files: I'll ask. Plan B could always be a script that just downloads the files, right?
As for the patch with the @TERMUX@ prefix: As far as I can see, all you did was search/replace any occurence of /usr/local with it, right?

**Comment by Grimler91** [comment]
> Plan B could always be a script that just downloads the files, right?

Yeah, looked at it that as well, https://msmemorial.if-legends.org does not allow scripted downloads though, trying to curl the files just gives a message that it is not allowed, but we can create another mirror for them where termux users can download them

> all you did was search/replace any occurence of /usr/local with it, right?
Yeah, that is exactly what I did :)
